### ISSUE TITLE
isValid is not a function

### ISSUE THREAD

**Issue by tm1000** [jsmreese/moment-duration-format#103]
```
moment.duration(123, "minutes").format();
moment-duration-format-2.2.1.js?load_version=v14.0.2.1:733 Uncaught TypeError: this.isValid is not a function
    at vb.durationFormat [as format] (moment-duration-format-2.2.1.js?load_version=v14.0.2.1:733)
    at <anonymous>:1:33
```

I can't see this function anywhere in the code. Not sure if moment is supposed to supply it?

**Comment by jsmreese** [comment]
Off the top of my head I'd guess that `isValid` was added in a recent version of moment and you're using an older version.

Updating moment should fix the issue, but I'll do some testing with older moment versions. Not sure if this is the only issue.

**Comment by tm1000** [comment]
@jsmreese huzzah! Thank you for the quick response. I looked in moment and I saw isValid() before opening this but alas you were 100% right. Upgrading from 2.15 to 2.20 solved this issue
