### ISSUE TITLE
Change log between versions

### ISSUE THREAD

**Issue by pribeirojtm** [jsmreese/moment-duration-format#105]
Hi,

I'm currently using 1.3.0 version. 
I want to know if it is safe to upgrade to the latest version without breaking the site. 
Is there any guide or page that shows new features/deprecation's/Backwards incompatibilities or so?

Thanks

**Comment by jsmreese** [comment]
The [releases](https://github.com/jsmreese/moment-duration-format/releases) page is pretty complete with respect to fixes, new features, and breaking changes for each version.

Version 2 is meant to be a nearly drop-in replacement for version 1. The [2.2.0 release page](https://github.com/jsmreese/moment-duration-format/releases/tag/2.0.0) has the specifics for breaking changes.

There were a number of unanticipated issues from moving to formatting with `toLocaleString` (unanticipated by me, at least), but those have been resolved. You should be good to go with the latest version.

**Comment by pribeirojtm** [comment]
thanks
