### ISSUE TITLE
Whole minutes and seconds display ambiguously

### ISSUE THREAD

**Issue by erickco** [jsmreese/moment-duration-format#14]
Formatting a duration of whole minutes results in only the minutes as digits.

So a duration of say 600 seconds will be formatted as "10" and a duration is 10 seconds is also formatted at "10". 
I would have expected the 600s to show as "10:00" or perhaps "10m" - and the 10s as "00:10" or "10s"

**Comment by jsmreese** [comment]
The moment maintainers had a few issues with my plan to save and access the input data on a moment object. I should have time to revisit this issue in the coming week, and I hope to have this addressed soon in a version 2.0.0 release of this plugin.

**Comment by jacobg** [comment]
Sort of related:
```
moment.duration('0:15').format('hh:mm')
// 15
```

I would have expected "00:15".

What's your ETA on 2.0 release? Thanks.

**Comment by jacobg** [comment]
Oh never mind, my last comment. The following settings fixes that:
```
moment.duration.fn.format.defaults.trim = false
```

**Comment by jsmreese** [comment]
@jacobg: ETA on 2.0 release... right! Should really get back around to that!

**Comment by avalanche1** [comment]
@jacobg , oh THANKS, mate!
