### ISSUE TITLE
Support rounding up

### ISSUE THREAD

**Issue by innokenty-shuvalov** [jsmreese/moment-duration-format#19]
When you output only the higher unit types (like years or hours, depending on the data you've got) it's usually expected that you round the value not always down, but sometimes up. For example 
```
moment.duration(123, "minutes").format("h [h]");
``` 
must result into ```"2 h"``` anyway, but 
```
moment.duration(179, "minutes").format("h [h]");
``` 
is usually expected (in real life) to result into ```"3 h"```, not  ```"2 h"```. 

Of course, this option should be optional, like:
```
moment.duration(179, "minutes").format("h [h]");
// "2h"
moment.duration(179, "minutes").format("h [h]", { allowRoundUp: true });
// "3h"
```

**Comment by jsmreese** [comment]
My dev branch is version 2.0.0 in progress.
I've changed the default behavior to `round` instead of `trunc`.
And I've added a `trunc` option -- set it to `true` to get the old truncate behavior.
