### ISSUE TITLE
Using with moment-timezone

### ISSUE THREAD

**Issue by msamblanet** [jsmreese/moment-duration-format#23]
I use moment-timezone and would also like to use moment-duration-format - but moment-timezone loads its own copy of moment, so the copy you patch for moment-duration-format is not the same one that has the moment-timezone added.

I have been able to work around the issue with the code below - but a more direct approach would be nice...any chance you could export an initializer to which I could pass the moment instance we want the plugin applied to?

```js
require("moment-duration-format");
var momentTimezone = require("moment-timezone");
momentTimezone.duration = require("moment").duration;
```

**Comment by jsmreese** [comment]
I've rearranged things so that I now export an initializer function. So now this would work:
```
var momentDurationFormat = require("moment-duration-format");
var momentTimezone = require("moment-timezone");

// setup Moment Duration Format function on the momentTimezone instance
momentDurationFormat(momentTimezone);
```

Does that work for you?
You can find the updated version in my dev branch.
I haven't tested it as a module yet but it's working as a browser global (famous last words).

**Comment by msamblanet** [comment]
I tried it in my node app via your dev branch and it seems to be working for me.  Thanks...

**Comment by jsmreese** [comment]
Awesome. Thanks for testing it.
