### ISSUE TITLE
Please update to be compatible with Moment 2.10

### ISSUE THREAD

**Issue by artknight** [jsmreese/moment-duration-format#28]

**Comment by cb1kenobi** [comment]
+1

**Comment by cesarandreu** [comment]
+1

**Comment by four43** [comment]
+1

Getting an error: 

Uncaught TypeError: Cannot set property 'format' of undefined

From: https://github.com/jsmreese/moment-duration-format/blob/master/lib/moment-duration-format.js#L202

**Comment by noseglid** [comment]
+1

**Comment by artknight** [comment]
Yes, it did get fixed in Moment 2.10.2.
