### ISSUE TITLE
Only show the minute part 'mm' results in total number of minutes

### ISSUE THREAD

**Issue by SamVerschueren** [jsmreese/moment-duration-format#30]
Hi

It's possible that I missed something in the documentation but this is what I have

```JavaScript
moment.duration(356, 'minutes').format('mm');
```

356 minutes is 5h56m. The format results in ```356``` instead of ```56```. If I have the following code:

```JavaScript
moment.duration(356, 'minutes').format('h:mm');
```

This will result in ```5:56```. But I don't need the hour part, only the minutes part. How can I solve this?

**Comment by GermainBergeron** [comment]
`moment.duration(356, 'minutes').minutes()`

**Comment by SamVerschueren** [comment]
Thanks!
