### ISSUE TITLE
Problem using 1.3 together with moment 2.10.2

### ISSUE THREAD

**Issue by mrft** [jsmreese/moment-duration-format#31]
Nodejs 0.10.25

<pre>
console.log( "MOMENTS: " + moment.duration( 3, 'minutes' ) + " " + moment.duration( 3, 'minutes' ).format( 'hh:mm' ) + " " + moment.duration( 3, 'minutes' ).format( 'hh:mm:ss' ) + " " + moment.duration( 3, 'minutes' ).format( ) )
</pre>

prints

<pre>
MOMENTS: 180000 03 03:00 3
</pre>

This doesn't look like what is being explained in the README (and is not what I want either).
What's wrong?

**Comment by jsmreese** [comment]
Sorry for the delay, but actually that all looks like the expected output.
If this is still an issue, what are you expecting to happen?

**Comment by mrft** [comment]
That is a long time ago, and I don't even remember where I needed this :)

but looking at it again

<pre>moment.duration( 3, 'minutes' ).format( 'hh:mm' )</pre>

shouldn't that return 00:03 instead of 03, or is that just my opinion?

**Comment by jsmreese** [comment]
Lots of different possible outputs for this:

```
hh:mm --> 03
h:mm --> 3
hh:mm, trim: false --> 00:03
h:mm, trim: false --> 0:03
```

The number of characters used in the first token (one, or more than one) will change the output, even when trimming. The default behaviour tries to output as few characters as possible :)

**Comment by mrft** [comment]
<pre>trim: false</pre>

Ahaa!
Thanks.
