### ISSUE TITLE
Formatting issues

### ISSUE THREAD

**Issue by ppumkin** [jsmreese/moment-duration-format#32]
I calculate diff in a loop for an unknown number of times and get the seconds back

It may be 0 or more.

When 0 it shows

`00`
when minutes come in
`01:01`
when hours come in
`01:01:01`

I am using format

`moment.duration(_diff, "seconds").format("hh:mm:ss", { forceLength: true });`

I want it to show this if zero seconds

`00:00:00`

I want it to show if minutes

`00:02:23`

The plugin is really great but why on earth would you want to rewrite the formatting functions, in a strange formatting "template" syntax?

If I specify `hh:mm:ss`  I want it to show `00:00:00` as in .NET/ Java / Python even moment does it.

If I wanted only seconds to show using that format, then I would check if the seconds are <60 and format it using `ss`, yea? 

Is there any work-around for this, use moment formatter instead? 
I am extremely picky on how the text is padded and displayed.

Great job on the moment.duration plugin +1  not so great trying to rewrite date formatting :(

**Comment by wboyle01** [comment]
I just ran into the same problem where only my seconds bit was display, but if you pass as part of the configuration {trim: false}, the format you want (00:00:00) will show up.

**Comment by SamFromDaUk** [comment]
I also have this problem and used the same configuration as wboyle01 to fix my issue

`moment.duration(5000).format('mm:ss', { trim: false })`

**Comment by jsmreese** [comment]
Sorry for the delay on this... updated my github notifications when I started a new job in March and I've missed a lot happening on this project.

As noted, the solution to this is to use `{ trim: false }`.
If you _really_ don't like my default trim feature, you can globally turn it off with `moment.duration.fn.format.defaults.trim = false;`.

The rationale for the trim feature comes from my work on web-based metrics dashboards at my last job. The idea is that if information isn't important, don't put it on the screen. Leading zeros, especially in a table column (which was the original application of this plugin), just serve to obscure the real data.
