### ISSUE TITLE
Issue when using with fullcalendar.io

### ISSUE THREAD

**Issue by d53dave** [jsmreese/moment-duration-format#36]
After including moment-duration-format.js I get following error on Chrome (Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.152 Safari/537.36) when rendering the calendar. 

`Uncaught TypeError: Cannot read property 'hasTime' of undefined`

Fullcalendar depends on moment.js but I did not dig deeper to find the root cause of the problem.

**Comment by jay7134** [comment]
i have same issue, please help

**Comment by daviwil2** [comment]
There appears (I stress appears) to be a bug in the 'addEventSource' code. To verify I've created an array called eventSources and if I specify eventSources: eventSources as an option when I instantiate fullCalendar then they render fine; if I change this to eventSources: [] and then after the instantiation and attach is completed I then do a $('#fullCalendar').fullCalendar('addEventSource', eventSources) I get the same error.  So works as a parameter, not when calling the function.  Not good.

**Comment by jsmreese** [comment]
While I've used fullcalendar, it's been more than a few years.
It looks like this is/was an issue with fullcalendar?
If it's still an unresolved problem, let me know and I may be able to take a look at it.

**Comment by wuqinqiang** [comment]
I can't find this error and that my code
![image](https://user-images.githubusercontent.com/36129334/49267427-6ebd3c00-f495-11e8-9d47-a7873b79aeb1.png)
![image](https://user-images.githubusercontent.com/36129334/49267431-7b419480-f495-11e8-9ad0-04f63b7e4e4b.png)
