### ISSUE TITLE
Over 30 days does not work

### ISSUE THREAD

**Issue by TakanashiOuken** [jsmreese/moment-duration-format#39]
moment.duration(29, "days").format()
"29d" => correct
moment.duration(30, "days").format()
"0m" => Should be "30d" 
moment.duration(60, "days").format()
"1m" => Should be "60d"
moment.duration(90, "days").format()
"2m" => Should be "90d"

**Comment by moses-seeq** [comment]
+1

**Comment by moses-seeq** [comment]
moment.duration(duration).format('d'), with the duration being milliseconds, is an effective work around for me, but I18N would be very beneficial, otherwise I have to roll my own.

**Comment by jsmreese** [comment]
This is working as expected with the default format function.
`moment.duration(90, "days").format("d[d]")` gives the output you want... and you're free to supply your own default format function via `moment.duration.fn.format.defaults.template`.
