### ISSUE TITLE
Is there a setting to round value before formatting it?

### ISSUE THREAD

**Issue by jacobg** [jsmreese/moment-duration-format#41]
Consider the following case:
```javascript
moment.duration.fn.format.defaults.trim = false;
moment.duration('0:15:45').format('hh:mm');   // "00:15"
```
The format function is truncating the duration value rather than rounding it. In the case above, it would be more accurate to round it first, and display "00:16". Is there a setting to do that?

**Comment by jacobg** [comment]
I implemented a solution. Basically, put the following code in the format function right before the each loop that calculates the value for each token:

```javascript
		// round to least significant token
		if (settings.round) {
			var leastToken = momentTypes.slice(-1)[0],
				roundedUnits = parseFloat(remainder.as(leastToken).toFixed(settings.precision));

			remainder = moment.duration(roundedUnits, leastToken);
		}
``` 

Will you put that in or accept a pull request? Thanks.

**Comment by jsmreese** [comment]
Check out my dev branch. I added this feature in 65bde6d59f17dcf15842e032f9ae97da6b0f2bed and made rounding the default behavior.

I'll try to get a new version of this plugin officially published soon.
