### ISSUE TITLE
Request: Take input as a duration string

### ISSUE THREAD

**Issue by CalebKester** [jsmreese/moment-duration-format#42]
It'd be great if this plugin supported input from the html5 duration format.

`PT23H 9M 2.343S` =  23 hours, 9 minutes and 2.345 seconds

Would this be a feature worth having? I'm pulling my data from html and would love to have the html match the spec (e.g. `<time datetime="PT@(seconds)S" class="js-momentDuration"></time>`). If so I can work on a pull request.

See:
http://www.brucelawson.co.uk/2012/best-of-time/
http://www.w3.org/TR/html-markup/time.html

**Comment by jsmreese** [comment]
You want to be able to do something like `moment.duration("PT23H 9M 2.343S").format()`?
As in, pass that HTML5 duration format into `Moment.Duration`?

**Comment by CalebKester** [comment]
Sorry for the delay in getting back to you. Yes that's exactly what I wanted! I didn't realize it worked like that, 

One thing I did notice is you can't pass spaces in `moment.duration("PT23H 9M 2S").format("h:mm:ss")` doesn't seem to work but `moment.duration("PT23H9M2S").format("h:mm:ss")` works. W3 doesn't mention anything about spaces so I guess that's up to spec? I'm guessing the brucelawson article might be wrong? Anyways, it seems to be working so I'll just close this. 

Thanks!
