### ISSUE TITLE
Only show the minute part when hour equals 0.

### ISSUE THREAD

**Issue by RWander** [jsmreese/moment-duration-format#43]
`moment.duration(1800, 'seconds').format('hh:mm')` returns _30_ but I expect _00:30_. Is there any way to do it?

**Comment by jsmreese** [comment]
`moment.duration(1800, 'seconds').format('hh:mm', { trim: false })` should do what you want.

**Comment by jsmreese** [comment]
The default behaviour is to trim leading zero-value tokens from the formatted output.

**Comment by RWander** [comment]
Thanks! I will try.
