### ISSUE TITLE
Rounding Milliseconds Incorrectly

### ISSUE THREAD

**Issue by breynolds** [jsmreese/moment-duration-format#50]
3:43.977 with a precision of 2 is formatted incorrectly as 3:43.97. It should be 3:43.98. Can't use a pattern to hide/show values. Have to implement rounding.

**Comment by jsmreese** [comment]
You'll find that this is correct on my `dev` branch.
I implemented rounding there as the default, with truncation as a configurable option instead.

Really should get that buttoned up and published, it being over a year old, but life happens and here we are.
