### ISSUE TITLE
"-" sign trimmed if minutes is negative but more than -60 and hours token is in format

### ISSUE THREAD

**Issue by VTimofeenko** [jsmreese/moment-duration-format#53]
I am writing a small reformatter, that discards all token except the two leftmost meaningful ones, i.e.:
- 1 year 1 month 1 day => '1y 1m'
- 1 month 1 day 1 hour => '1m 1d'

```
moment.duration({'minutes': -10}).format('h[H] m[M]')
"10M"
```

While "-10M" would be expected, like:

```
moment.duration({'minutes': -10}).format('m[M]')
"-10M"
```

While positive values are trimmed correctly:

```
moment.duration({'minutes': 10}).format('h[H] m[M]')
"10M"
```

Same applies when a "bigger" token is present in format string while the passed duration is more than the negative "bigger" token. This is illustrated by:

```
moment.duration({'hours': -1, 'minutes': -10}).format('h[H] m[M]')
"-1H 10M"
moment.duration({'hours': -1, 'minutes': -10}).format('d[D] h[H] m[M]')
"1H 10M"
```

Or should such cases be handled manually in my use case?

**Comment by jsmreese** [comment]
I'd done some work on negative durations a while ago, and this issue is fixed in the plugin version now on the master branch. I should have it published soon.
