### ISSUE TITLE
Strange conversion

### ISSUE THREAD

**Issue by mspe87** [jsmreese/moment-duration-format#56]
Im trying to convert this:
86532 minutes 
but getting:
(1M 4w 2d 2h:12m)
 im using format("y[y] M[M] w[w] d[d] h[h]:mm[m]")

Why is it not rendering 2M 0w ?

**Comment by jasonlemay** [comment]
Based on Google, the output you get seems to be right : 

![image](https://cloud.githubusercontent.com/assets/2584073/19403071/cdcc2994-9232-11e6-8e85-0ba5b44ab1de.png)

2 months = 87600.1 mn

![image](https://cloud.githubusercontent.com/assets/2584073/19403118/120c3da6-9233-11e6-8847-12b2d05dd2b6.png)

**Comment by jsmreese** [comment]
And based on moment itself:
```
moment.duration(2, "months").format("m [minutes]");
//"87,840 minutes"
```
