### ISSUE TITLE
format doesn't round prior to slicing

### ISSUE THREAD

**Issue by skoblenick** [jsmreese/moment-duration-format#59]
The decimal value is not being rounded prior to slicing which causes the time to be incorrect in the following cases.

```
equal(moment.duration(70300, "milliseconds").format("s", 1), "70.3");           // fails with 70.2
equal(moment.duration(288957, "milliseconds").format("s", 1), "289.0");      // fails with 288.9
equal(moment.duration(1087300, "milliseconds").format("s", 1), "1087.3");   // fails with 1087.2
```

**Comment by jonnybi** [comment]
Any idea how to avoid this?

**Comment by jsmreese** [comment]
Not sure exactly when this was fixed, but I've just added these tests to the latest plugin version on the master branch, and they all pass.

**Comment by jpuffer** [comment]
👏   Thanks for the fix!
