### ISSUE TITLE
Parsing seems broken

### ISSUE THREAD

**Issue by bendavis78** [jsmreese/moment-duration-format#77]
Not sure whether or not this is an issue with moment core, but the following use case is broken:

    moment.duration('5:30', 'm:ss', true);

should result in 5 minutes 30 seconds, but instead it results in 5 hours 30 minutes.

**Comment by jsmreese** [comment]
Not sure if that ever worked, but it certainly doesn't now...
From moment itself, the duration constructor only takes two arguments:
```
function createDuration (input, key)
```
https://momentjs.com/docs/#/durations/

And from what I can tell the second argument is a unit of measurement as defined in moment, e.g. `minutes` or `seconds` or a shorthand unit, e.g. `m` or `s`. It doesn't look like a format string is supported there.

My plugin doesn't affect parsing of duration strings in `moment.duration`!

**Comment by bendavis78** [comment]
Makes sense. Thanks!
