### ISSUE TITLE
forceLength is ignored when formatting milliseconds

### ISSUE THREAD

**Issue by mathiasjakobsen** [jsmreese/moment-duration-format#80]
```js
const duration = moment.duration(5.6789101112, 'seconds').format('mm:ss:SS', {
  trim: false,
  forceLength: true
})
```
will output `00:05:678` instead of expected `00:05:67` ⌛️

**Comment by jsmreese** [comment]
This behaviour is updated in version 2.0.0, which is *almost* done, and not yet published.
On version 1.3 you get the issue you see. On version 2, you'll get the output you expect.

I'll hopefully have it published in the next few days, but in the interim, you can use the plugin version currently on the master branch.

**Comment by mathiasjakobsen** [comment]
@jsmreese Thanks 🍻
