### ISSUE TITLE
Negative values are handled incorrectly when using `stopTrim`

### ISSUE THREAD

**Issue by pediredla** [jsmreese/moment-duration-format#86]
moment.duration(-600, 'seconds').format('hh:mm', {stopTrim: 'h m', forceLength: true}) 

outputs 00:10 and not -00:10.

is this an expected behaviour?

**Comment by jsmreese** [comment]
Yikes! Nope, certainly not expected. Not sure why the existing negative duration tests don't catch this one, but I'll take a look.
